### ISSUE TITLE
运行python app.py --transport webrtc卡住在warm-up done

### ISSUE THREAD

**Issue by BiboyQG** [lipku/LiveTalking#187]
按ctrl c 后报错如下：
```
      (0): Linear(in_features=36, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=1, bias=False)
    )
  )
  (aud_ch_att_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=36, out_features=64, bias=False)
      (1): Linear(in_features=64, out_features=32, bias=False)
    )
  )
  (torso_deform_encoder): FreqEncoder: input_dim=2 degree=8 output_dim=34
  (anchor_encoder): FreqEncoder: input_dim=6 degree=3 output_dim=42
  (torso_deform_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=84, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=32, bias=False)
      (2): Linear(in_features=32, out_features=2, bias=False)
    )
  )
  (torso_encoder): GridEncoder: input_dim=2 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(555520, 2) gridtype=tiled align_corners=False
  (torso_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=116, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=32, bias=False)
      (2): Linear(in_features=32, out_features=4, bias=False)
    )
  )
)
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
[INFO] Trainer: ngp | 2024-08-05_07-16-57 | cuda | fp16 | data/video
[INFO] #parameters: 1789121
[INFO] Loading data/pretrained/ngp_kf.pth ...
[INFO] loaded model.
[INFO] load at epoch 28, global step 203616
[WARN] Failed to load optimizer.
[INFO] loaded scheduler.
[INFO] loaded scaler.
[INFO] load 7272 frames.
Loading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7272/7272 [00:00<00:00, 143078.86it/s]
[INFO] eye_area: 0.0 - 1.0
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
/home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
[INFO] warm up ASR live model, expected latency = 0.560000s
[INFO] warm-up done, actual latency = 0.901774s
^CTraceback (most recent call last):
  File "/home/biboy/DL/metahuman-stream/app.py", line 449, in <module>
    run_server(web.AppRunner(appasync))
  File "/home/biboy/DL/metahuman-stream/app.py", line 447, in run_server
    loop.run_forever()
  File "/home/biboy/miniconda3/envs/meta/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/home/biboy/miniconda3/envs/meta/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/biboy/miniconda3/envs/meta/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```

**Comment by BiboyQG** [comment]
```
    (0): Linear(in_features=36, out_features=32, bias=False)
    (1): Linear(in_features=32, out_features=1, bias=False)
  )
 ) (aud_ch_att_net): MLP( (net): ModuleList( (0): Linear(in_features=36, out_features=64, bias=False) (1): Linear(in_features=64, out_features=32, bias=False) ) ) (torso_deform_encoder): FreqEncoder: input_dim=2 degree=8 output_dim=34 (anchor_encoder): FreqEncoder: input_dim=6 degree=3 output_dim=42 (torso_deform_net): MLP( (net): ModuleList( (0): Linear(in_features=84, out_features=32, bias=False) (1): Linear(in_features=32, out_features=32, bias=False) (2): Linear(in_features=32, out_features=2, bias=False) ) ) (torso_encoder): GridEncoder: input_dim=2 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(555520, 2) gridtype=tiled align_corners=False (torso_net): MLP( (net): ModuleList( (0): Linear(in_features=116, out_features=32, bias=False) (1): Linear(in_features=32, out_features=32, bias=False) (2): Linear(in_features=32, out_features=4, bias=False) ) ) ) Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] /home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead. warnings.warn( /home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) Loading model from: /home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth [INFO] Trainer: ngp | 2024-08-05_07-16-57 | cuda | fp16 | data/video [INFO] #parameters: 1789121 [INFO] Loading data/pretrained/ngp_kf.pth ... [INFO] loaded model. [INFO] load at epoch 28, global step 203616 [WARN] Failed to load optimizer. [INFO] loaded scheduler. [INFO] loaded scaler. [INFO] load 7272 frames. Loading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7272/7272 [00:00<00:00, 143078.86it/s] [INFO] eye_area: 0.0 - 1.0 [INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto... /home/biboy/miniconda3/envs/meta/lib/python3.10/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`. warnings.warn( [INFO] warm up ASR live model, expected latency = 0.560000s [INFO] warm-up done, actual latency = 0.901774s ^CTraceback (most recent call last): File "/home/biboy/DL/metahuman-stream/app.py", line 449, in run_server(web.AppRunner(appasync)) File "/home/biboy/DL/metahuman-stream/app.py", line 447, in run_server loop.run_forever() File "/home/biboy/miniconda3/envs/meta/lib/python3.10/asyncio/base_events.py", line 603, in run_forever self._run_once() File "/home/biboy/miniconda3/envs/meta/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once event_list = self._selector.select(timeout) File "/home/biboy/miniconda3/envs/meta/lib/python3.10/selectors.py", line 469, in select fd_event_list = self._selector.poll(timeout, max_ev)
```

**Comment by jin1wang** [comment]
同样的问题，有解决吗
