### ISSUE TITLE
edge tts貌似完全挂了

### ISSUE THREAD

**Issue by TigerHH6866** [lipku/LiveTalking#280]
Exception in thread Thread-2 (process_tts):
Traceback (most recent call last):
  File "E:\metahuman-stream\venv\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\metahuman-stream\venv\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\metahuman-stream\ttsreal.py", line 53, in process_tts
    self.txt_to_audio(msg)
  File "E:\metahuman-stream\ttsreal.py", line 66, in txt_to_audio
    asyncio.new_event_loop().run_until_complete(self.__main(voicename,text))
  File "E:\metahuman-stream\venv\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\metahuman-stream\ttsreal.py", line 106, in __main
    async for chunk in communicate.stream():
  File "E:\metahuman-stream\venv\lib\site-packages\edge_tts\communicate.py", line 391, in stream
    async with aiohttp.ClientSession(
  File "E:\metahuman-stream\venv\lib\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "E:\metahuman-stream\venv\lib\site-packages\aiohttp\client.py", line 947, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=a948023e557544d3bba7da5b42f37259'

**Comment by shruak** [comment]
同样的问题 有什么办法了吗

**Comment by ForLuna1998** [comment]
> 同样的问题 有什么办法了吗

更新edge-tts到6.1.13可以解决

**Comment by kryst5l** [comment]
更新了之后，发现edge_tts和视频合成后，有点问题，数字人好像不说话了

**Comment by chenkai89** [comment]
换成其他音频推理吧，今天试了，哪个版本都不行

**Comment by creampnx-x** [comment]
换成 GPT-SoVITs 吧，挺好用的

**Comment by seamo-sun** [comment]
换成 GPT-SoVITs 数字人也不说话

**Comment by Louis-ThibaultK** [comment]
遇到同样的问题

**Comment by chenkai89** [comment]
我最近发现了一个项目，使用6.1.17版本可以正常生成语音




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lipku/LiveTalking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月23日(星期一) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lipku/LiveTalking] edge tts貌似完全挂了 (Issue #280)





 
遇到同样的问题

**Comment by lipku** [comment]
安装最新版的edgetts可以
