### ISSUE TITLE
Gpt-sovits返回语言后报错

### ISSUE THREAD

**Issue by YuChuanhui3** [lipku/LiveTalking#281]
gpt_sovits Time to first chunk: 4.470286976080388s
------actual avg final fps:17.4569
sleep qsize= 10
gpt_sovits response.elapsed: 0:00:00.006730
sleep qsize= 17
Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Desktop/metahuman-stream-new/metahuman-stream-gai/lipreal.py", line 125, in inference
    pred = model(mel_batch, img_batch)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/Desktop/metahuman-stream-new/metahuman-stream-gai/wav2lip/models/wav2lip_v2.py", line 139, in forward
    x = f(x)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/Desktop/metahuman-stream-new/metahuman-stream-gai/wav2lip/models/conv.py", line 16, in forward
    out = self.conv_block(x)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (4 x 4). Kernel size can't be greater than actual input size

**Comment by malikcoachhub** [comment]
Hi, Did you able to solve that issue? @YuChuanhui3

**Comment by Shirley-0708** [comment]
Hi, did you solve the problem? @malikcoachhub @YuChuanhui3

**Comment by malikcoachhub** [comment]
yes @Shirley-0708 .. don't update --img_size .. put it 384 and it should work

**Comment by YuChuanhui3** [comment]
I solved this problem in the genavatar.py file by setting the default value of img_size to 256
