### ISSUE TITLE
发送文本后，视频卡住，然后控制台报错

### ISSUE THREAD

**Issue by vingin007** [lipku/LiveTalking#294]
环境：pytorch2.1，torchvision0.16
问题：可以正常推流到srs并在网页播放，但是一旦发送文本后，视频就会卡住不动。并且控制台报错。看错误是需要GPU运行？需要在哪里设置吗
/home/ubuntu/MetaHuman/LiveTalking/musetalk/whisper/whisper/transcribe.py:79: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Process Process-1:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/MetaHuman/LiveTalking/musereal.py", line 104, in inference
    pred_latents = unet.model(latent_batch,
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1143, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/diffusers/models/embeddings.py", line 807, in forward
    sample = self.linear_1(sample)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/nerfstream/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
------actual avg final fps:24.9950

**Comment by vingin007** [comment]
解决了，是GPT-SoVITS那边少了个库，导致语音没有合成成功
