### ISSUE TITLE
传入的对象None,这是为啥

### ISSUE THREAD

**Issue by surespace1** [lipku/LiveTalking#312]
start http server; http://<serverip>:8010/rtcpushapi.html
Error: Cannot connect to host localhost:1985 ssl:default [Connect call failed ('127.0.0.1', 1985)]
Traceback (most recent call last):
  File "/home/ai/PycharmProjects/xuexi/LiveTalking/app.py", line 563, in <module>
    run_server(web.AppRunner(appasync))
  File "/home/ai/PycharmProjects/xuexi/LiveTalking/app.py", line 560, in run_server
    loop.run_until_complete(run(opt.push_url))
  File "/home/ai/miniconda3/envs/lwm/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ai/PycharmProjects/xuexi/LiveTalking/app.py", line 300, in run
    await pc.setRemoteDescription(RTCSessionDescription(sdp=answer,type='answer'))
  File "/home/ai/miniconda3/envs/lwm/lib/python3.10/site-packages/aiortc/rtcpeerconnection.py", line 829, in setRemoteDescription
    description = sdp.SessionDescription.parse(sessionDescription.sdp)
  File "/home/ai/miniconda3/envs/lwm/lib/python3.10/site-packages/aiortc/sdp.py", line 385, in parse
    session_lines, media_groups = grouplines(sdp)
  File "/home/ai/miniconda3/envs/lwm/lib/python3.10/site-packages/aiortc/sdp.py", line 141, in grouplines
    for line in sdp.splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by aabighead** [comment]
你好，我也遇到了这个问题，请问解决乱码

**Comment by aabighead** [comment]
你好，我也遇到这个问题，请问解决了吗
