### ISSUE TITLE
module 'torch' has no attribute 'float8_e4m3fn'

### ISSUE THREAD

**Issue by kkkwjr** [lipku/LiveTalking#340]
今天运行的时候环境突然崩了，有人知道怎么解决吗，万分感谢！
For example: export FFMPEG_PATH=/musetalk/ffmpeg-4.4-amd64-static
Traceback (most recent call last):
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/models/autoencoders/__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 22, in <module>
    from ..modeling_utils import ModelMixin
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/quantizers/__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/quantizers/auto.py", line 31, in <module>
    from .torchao import TorchAoHfQuantizer
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/quantizers/torchao/__init__.py", line 15, in <module>
    from .torchao_quantizer import TorchAoHfQuantizer
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/quantizers/torchao/torchao_quantizer.py", line 43, in <module>
    torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/kkkjr/Item/LiveTalking/app.py", line 744, in <module>
    from musereal import MuseReal
  File "/workspace/kkkjr/Item/LiveTalking/musereal.py", line 21, in <module>
    from musetalk.utils.utils import get_file_type,get_video_fps,datagen
  File "/workspace/kkkjr/Item/LiveTalking/musetalk/utils/utils.py", line 15, in <module>
    from musetalk.models.vae import VAE
  File "/workspace/kkkjr/Item/LiveTalking/musetalk/models/vae.py", line 1, in <module>
    from diffusers import AutoencoderKL
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/wpg/anaconda3/envs/livestream/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'

**Comment by kkkwjr** [comment]
Traceback (most recent call last):
  File "/workspace/kkkjr/Item/LiveTalking/app.py", line 744, in <module>
    from musereal import MuseReal
  File "/workspace/kkkjr/Item/LiveTalking/musereal.py", line 2, in <module>
    import torch
  File "/home/wpg/anaconda3/envs/nerfstream/lib/python3.10/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: libnvJitLink.so.12: cannot open shared object file: No such file or directory

先会出现这个错，然后降级了torch之后会出现module 'torch' has no attribute 'float8_e4m3fn'

**Comment by shou-heng** [comment]
你好，解决了吗，我也出现了
