### ISSUE TITLE
set_audiotype切换同一个视频第二遍会报错

### ISSUE THREAD

**Issue by bigai-wwb** [lipku/LiveTalking#344]
使用接口set_audiotype或调用下面两句
sessionid = params.get('sessionid', 0)
nerfreals[sessionid].set_curr_state(2, False)

会出现下面错误，导致整个绘制停止。

`Exception in thread Thread-3 (process_frames):
Traceback (most recent call last):
  File "E:\Software\Anaconda3\envs\LiveTalking-main\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\Software\Anaconda3\envs\LiveTalking-main\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Projects\LiveTalking-main\musereal.py", line 317, in process_frames
    new_frame.planes[0].update(frame.tobytes())
IndexError: tuple index out of range`

打印了一下
print(len(frame),"   ",type)
0     1

正常情况是
320     1
切换正常是
320     2

不太清楚这里是什么原因

**Comment by bigai-wwb** [comment]
改了，是否从头开始播放的设置
